language: python
python:
    - "3.6"

addons:
  apt:
    packages:
      - docker-ce

services:
  - docker

cache:
  directories:
  - /home/travis/docker/

env:
  global:
    - DOCKER_CACHE_FILE=/home/travis/docker/cache.tar.gz

before_install:
  - pip3 install dropbox
  - docker build -t cv .

script:
- make docker-run


after_success:
- bash deploy.sh
#- python3 upload_file.py $DROPBOX_TOKEN $(find / -name "FrancescoArgentieri-Resume.pdf" 2>/dev/null)

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: FrancescoArgentieri-Resume.pdf
  release_notes: "Automatically build by Travis CI"
  on:
    repo: frank1789/CV

after_deploy:
- bash ./travis_push.sh

notifications:
  email:
    on_success: change
    on_failure: always
