language: generic

service:
  - docker

before_install:
  - docker build -t cv .

install:
  - docker save cv | gzip > docker/cv.tar.gz
cache:
  directories:
  - docker


script:
  - docker run -it -v ${PWD}:/cv cv
