os: linux
dist: focal

language: python
python:
  - "3.9"

services:
  - docker

cache:
  directories:
    - /home/travis/docker/

before_install:
  - pip3 install dropbox
  - docker build -t cv .

script:
  - make docker-run

after_success:
  - python3 upload_file.py $DROPBOX_TOKEN build/FrancescoArgentieri-Resume.pdf

before_deploy: 
  - bash deploy.sh

deploy:
  provider: releases
  token: $GITHUB_TOKEN
  file:
    - build/FrancescoArgentieri-Resume.pdf
    - FrancescoArgentieri-Resume.pdf
  release_notes: "Automatically build by Travis CI"
  skip_cleanup: true
  on:
    tags: true
    repo: frank1789/CV

after_deploy:
  - bash travis_push.sh

notifications:
  email:
    on_success: change
    on_failure: always
