language: generic

service:
  - docker

before_install:
  - docker build -t xelatex/cv .

install:
  - docker save xelatex | gzip > docker/xelatex.tar.gz
cache:
  directories:
  - docker

before_script:
  - gzip -dc docker/xelatex.tar.gz | docker load

script:
  - docker run -it -v ${PWD}:/cv xelatex/cv
