sudo: required
language: generic

service:
- docker

cache:
  bundler: true
  directories:
  - /home/travis/docker/

env:
  global:
    - DOCKER_CACHE_FILE=/home/travis/docker/cache.tar.gz

before_install:
  - sudo apt-get update
  - docker build -t cv .

script:
- docker run -it -v ${PWD}:/cv cv
- if [[ ${TRAVIS_BRANCH} == "master" ]] && [[ ${TRAVIS_PULL_REQUEST} == "false" ]]; then mkdir -p $(dirname ${DOCKER_CACHE_FILE}) ; docker save $(docker history -q ${DOCKER_REPOSITORY}:${TRAVIS_COMMIT}  | grep -v '<missing>') | gzip > ${DOCKER_CACHE_FILE}; fi

after_success:
- bash deploy.sh

deploy:
  provider: releases
  api_key:
    secure: a9Nb2zk8flfwDMqq1BxgVv0Zu49P/NVwnp64Bsq4UkO0ZiKbWrcnPB8TQXAquXHh3L7N8lZS3Y4sK89u15q7Zm42g79rxvsV+H/pUdXhe3EkXo0bW1nKEAvgN9UqEJwobLpClEstd8RRlmQAKFrqpFl5hMiodOrn0WVTC7e7XvsFqFe2XfpOmQiUSGHDjIb7el5MriNpwApOd00T+3AZRb5GlBLWKKU5RQDiWldLD+QlroR8ldUNC7UcDyVWfKi2rnHCXEKZzdIIjlzDLcufTOmTqBPw0dE4ksQfYSEZvMmD+7siwVxCS/RCnLN9XuO+qR+Skwc8TEWuwZBGLN0Ags3llHGsyR922wgElbiwK/qJvpJclFb4DGy9DSyfsZ4k3BilMNusXooKd/Z4CPqBvfHu3CXDtT/69gY6kxSLO+tSP/ua9Cji6E1MQyTdi0SnJiqoxlfM9i9Q4XkAGTwCcexi57syHT3jiGh6C0h1cC+/yLNJiWBzSisXAmtdVCEF/D8EPLtSN7jCh0yKksStksQ2+Be5SYfIS8kEckQ6Mcu8fb2V62AgOK/YwGjm9iaCjkLGCS8wYaaw3K19fcuAaUHDm13x+dpQnA2QAeOOdtURPFFdnS0T6TU1trpAP46zB1TVBeQ+GoSH111ICAkTQUKCpwpae1g2jD0Cd1ksMRE=
  file: FrancescoArgentieri-Resume.pdf
  body: "Automatically build by Travis CI"
  skip_cleanup: true
  on:
    repo: frank1789/CV
