
name: Compile CV and release PDF

on:
  push:
    branches: 
      - main
      - master

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Set up Pyhton
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - name: install dependecies
        run: |
          python -m pip install --upgrade pip
          pip install jinja2 dropbox
      - name: Prepare template
        run: |
          python resume.py information.json \
          --template Friggeri \
          --output FrancescoArgentieri-Resume.tex
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        env:
          TEXINPUTS: ".:./build//:"
        with:
          root_file: build/FrancescoArgentieri-Resume.tex
          path: FrancescoArgentieri-Resume.pdf
          glob_root_file: true
          latexmk_use_xelatex: true
          latexmk_shell_escape: true
