name: Compile CV and release PDF

on:
 push:
  branches: [ $default-branch ]
#     tags:
     

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Set up Pyhtone  
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Prepare template
        run: |
          pythonresume.py information.json \
          --template Friggeri \
          --output FrancescoArgentieri-Resume.tex
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: build/FrancescoArgentieri-Resume.tex
          glob_root_file: true
          latexmk_use_xelatex: true
          latexmk_shell_escape: true
